### ISSUE TITLE
Bug: carousel component tries to call setState of unmounted component because of autoplay set interval

### ISSUE THREAD

**Issue by IpShot** [kenwheeler/nuka-carousel#100]
We should to remove autoplay calls interval.
For this we need to call this.stopAutoplay() in componentWillUnmount().

**Comment by gmonte** [comment]
Hey! Two years later... I was the same problem today.
I created a middleware component to create Nuka Carousel. Everything is dinamic here. When I have just one slider item and autoplay is true, wrapAround is true and autoplayInterval is a number, this warning is shown. So I setted some parameters hardcode to work fine!
`javascript
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import NukaCarousel from 'nuka-carousel'
import { withStyles } from '@material-ui/core/styles'
import IconButton from '@material-ui/core/IconButton'
import NavigateBeforeIcon from '@material-ui/icons/NavigateBefore'
import NavigateNextIcon from '@material-ui/icons/NavigateNext'

import styles from './styles'

class Carousel extends Component {
  static getDerivedStateFromProps(props, state) {
    const { children } = props
    return {
      ...state,
      numberOfSliders: children.length
    }
  }

  constructor(props) {
    super(props)

    this.renderLeftControl = this.renderLeftControl.bind(this)
    this.renderRightControl = this.renderRightControl.bind(this)

    this.state = {
      numberOfSliders: 0
    }
  }

  renderLeftControl(previousSlide) {
    if (this.state.numberOfSliders < 2) { return null }

    const { classes } = this.props
    return (
      <IconButton
        onClick={ previousSlide }
        classes={ { root: classes.arrowButtonContainer } }
        aria-label="Anterior"
        color="primary"
      >
        <NavigateBeforeIcon classes={ { root: classes.arrowButtonIcon } } />
      </IconButton>
    )
  }

  renderRightControl(nextSlide) {
    if (this.state.numberOfSliders < 2) { return null }

    const { classes } = this.props
    return (
      <IconButton
        onClick={ nextSlide }
        classes={ { root: classes.arrowButtonContainer } }
        aria-label="Próximo"
        color="primary"
      >
        <NavigateNextIcon classes={ { root: classes.arrowButtonIcon } } />
      </IconButton>
    )
  }

  render() {
    const nukaProps = { ...this.props }

    const { numberOfSliders } = this.state

    nukaProps.autoplay = numberOfSliders > 1 && nukaProps.autoplay
    nukaProps.wrapAround = numberOfSliders > 1 && nukaProps.wrapAround
    nukaProps.autoplayInterval = numberOfSliders > 1 ? nukaProps.autoplayInterval : undefined

    return (
      <NukaCarousel
        { ...nukaProps }
        renderCenterLeftControls={
          ({ previousSlide }) => this.renderLeftControl(previousSlide)
        }
        renderCenterRightControls={
          ({ nextSlide }) => this.renderRightControl(nextSlide)
        }
      />
    )
  }
}

Carousel.propTypes = {
  children: PropTypes.arrayOf(PropTypes.element).isRequired,
  classes: PropTypes.object.isRequired
}

export default withStyles(styles)(Carousel)
`

**Comment by IpShot** [comment]
@gmonte Not sure you are about the same issue. For my issue solution was pretty simple https://github.com/IpShot/nuka-carousel/commit/e0a7547d19d026f3e6466867c90bb9f3dba6da2b.
