### ISSUE TITLE
Height is calculating incorrectly when using cellSpacing property

### ISSUE THREAD

**Issue by msevera** [kenwheeler/nuka-carousel#102]
When I setup carousel to be vertically without cellSpacing property, like this:
```
<Carousel slidesToShow={3} cellSpacing={0} vertical={true}>
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div>4</div>
    <div>5</div>
</Carousel>
```
and the css:
```
.slider-slide div{
    border: 1px solid red;
    height: 50px;
    width: 50px;
}
```

everything works as expected. So the carousel is shown like on this picture:
![image](https://cloud.githubusercontent.com/assets/2269852/16010517/36665ad8-318a-11e6-9072-4591cbe11f52.png)

But when I set cellSpacing property to some value (f.e. 10):
```
<Carousel slidesToShow={3} cellSpacing={10} vertical={true}>
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div>4</div>
    <div>5</div>
</Carousel>
```

Then carousel is look like this:
![image](https://cloud.githubusercontent.com/assets/2269852/16010557/6ae4f5b2-318a-11e6-84b4-6a6cedce77dc.png)
 As a result the last element is cut off.

I've investigated this issue a bit and found that css properties of the rule `.slider-slide` has position property set to absolute (previously it was set to static). This means that on a previous version of the carousel the slides had collapsible margins, but now they don't have this. F.e. in previous version when I set cellSpacing to 16, the 8px was added as margin-top and margin-bottom to slides, but between slides was 8px due to margin was collapsed . In current version, margins are not collapsed and between slides is 16px. The calculation of the carousel height is broken now, because expression to calculate carousel fame height has code `(props.cellSpacing / 2)`:
`frameHeight = slideHeight + ((props.cellSpacing / 2) * (props.slidesToShow - 1));`
I think if there was no dividing of the cellSpacing by two, then maybe it will work correctly.

We've done a workaround for this in our project (We've overridden position:absolute of the `.slider-slide` rule to be static), but this is temporary solution, and it's not ok for us. Please fix this issue ASAP in you carousel react component.

**Comment by cyppe** [comment]
+1

**Comment by Lukavyi** [comment]
+1

**Comment by kenwheeler** [comment]
Whoah, sorry about that! Absolute positioning was required for wrapAround to be possible, had a feeling some height stuff would pop up. Can you supply a gist that I can use to see the exact issue, so that I can verify I've fixed it?

**Comment by kenwheeler** [comment]
Just pushed a fix up to master, can you verify that it fixes your use case? If everything looks good I'll cut a patch release.

**Comment by msevera** [comment]
Hi.
I've just verified your fix and it works well. You can create a new version.

And Thank you :+1:

**Comment by kenwheeler** [comment]
awesome

**Comment by kenwheeler** [comment]
done
