### ISSUE TITLE
Add prop to remove arrows

### ISSUE THREAD

**Issue by moimael** [kenwheeler/nuka-carousel#118]
Hi,

It would be cool to have a prop to not show arrows/dots.

Thanks !

**Comment by lauterry** [comment]
To avoid showing arrows/dots, pass a prop ```decorators={[]}``` to the Carousel component.

**Comment by kenwheeler** [comment]
This ^

**Comment by Kerumen** [comment]
@kenwheeler Add this to the doc please!

**Comment by arximughal** [comment]
Above solution no longer works in `"nuka-carousel": "^4.3.5"`. 
But this does:
```
<Carousel
  renderCenterLeftControls={null}
  renderCenterRightControls={null}
>
... 
</Carousel>
```
This will remove the left right slide controls.

**Comment by AbhishekJaiswal123** [comment]
For removing the dots you can use  `renderBottomCenterControls={null}`
