### ISSUE TITLE
setCarouselData undefined

### ISSUE THREAD

**Issue by tvarner** [kenwheeler/nuka-carousel#122]
Hi, for some reason after following the instructions to add an external Controller to my carousels, `setCarouselData` is undefined. Not quite sure what, I'm doing wrong. My apologies if the answer is obvious, I'm relativly new to React. Help much appreciated, thanks. :)

The following code: 

`import React, {Component, PropTypes} from 'react';
import Carousel from 'nuka-carousel';`

`export default class Section extends Component { 
    mixins: [Carousel.ControllerMixin];
`
    `state = { 
        open: false,
        index: 0
    }

    render () {

        const style = require('./Accordion.scss');

        const handleClick = () => { 
            const _open = !this.state.open;
            this.setState({ open : _open });
        };

        const handleTopSlideSelection = (i) => { 
            console.log("top selected");
            console.log(this.state.carousels.top_carousel);
        };

        const handleBottomSlideSelection = () => { 
            console.log(i);
            console.log(this.state.carousels.bottom_carousel);
            // this.state.carousels.top_carousel.goToSlide.bind(null, i)
        };

        const numbers = [ "A", "B", "C", "D", "E" ];

        // const header_slides;

        const top_slides = numbers.map( (n, i) => {
            return (
                <div data-tag={i} onClick={handleTopSlideSelection.bind(null, i)}><h3>{n}</h3></div>
            );
        });

        const bottom_slides = numbers.map( (n, i) => {
            return (
                <div data-tag={i} onClick={handleBottomSlideSelection.bind(null, i)}><h3>{n}</h3></div>
            );
        });

        return (
            <div>
                <button className={style.accordion + ' ' + (this.state.open ? style.active : '')} onClick={handleClick} >Section 1</button>
                <div className={style.panel + ' ' + (this.state.open ? style.show : '')}>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    <Carousel ref="top_carousel" data={this.setCarouselData.bind(this, "top_carousel")} slidesToShow={1}>
                        {top_slides}
                    </Carousel>
                    <Carousel ref="bottom_carousel" data={this.setCarouselData.bind(this, "bottom_carousel")} slidesToShow={5}>
                        {bottom_slides}
                    </Carousel>
                </div>
            </div>
        );
    }} `

Produces the following error: 
`error given was: TypeError: Cannot read property 'bind' of undefined
[1]     at Section.render (Section.js:53:56)`

**Comment by tvarner** [comment]
Nvm. Figured it out. I'm using the following kit (https://github.com/erikras/react-redux-universal-hot-example), which required a slightly diff implementation. Thanks. :)

**Comment by stefanhza** [comment]
Hi @tvarner,

Can you share with me what the solution was? I'm having the same problem my side.

Thanks
