### ISSUE TITLE
Hide Default Controls

### ISSUE THREAD

**Issue by alkali47** [kenwheeler/nuka-carousel#14]
How do i hide the default controls (Prev, next and the bullets) ?

**Comment by kenwheeler** [comment]
you can pass Decorators={[]}

**Comment by alkali47** [comment]
I passed it to the Carousel Component, the controls still show

**Comment by kenwheeler** [comment]
oops, lowercase decorators

**Comment by alkali47** [comment]
It works now, awesome

**Comment by pkail** [comment]
That seems to be deprecated.  This works:

defaultControlsConfig={{
  prevButtonStyle: {
    opacity: '0',
  },
  nextButtonStyle: {
	opacity: '0'
}
}}
