### ISSUE TITLE
Are there any events when the slide index changes?

### ISSUE THREAD

**Issue by williamle8300** [kenwheeler/nuka-carousel#39]
(title)

**Comment by sarith** [comment]
Or even updating the carousels.carousel object with this data would be super helpful, i.e. `currentSlide`.

Right now, the Carousel component has this in its state, and provides functions to mutate it via the `Carousel.ControllerMixin`, but doesn't expose the `currentSlide` value.  Not sure if this is an anti-pattern or not (new to React).

What do you guys think?

**Comment by sarith** [comment]
Whoa - nevermind - just realized this can be accessed through `this.state.carousels.carousel.state.currentSlide` when using the `Carousel.ControllerMixin`.  I guess this whole mixin is sort of an anti-pattern anyways...
