### ISSUE TITLE
feature: autoplay? 

### ISSUE THREAD

**Issue by mmahalwy** [kenwheeler/nuka-carousel#44]

**Comment by mydearxym** [comment]
+1

**Comment by Bernoulli-IT** [comment]
+1

**Comment by mr47** [comment]
@mmahalwy @mydearxym @Bernoulli-IT your welcome https://github.com/mr47/nuka-carousel-autoscroll 

It's using some plugin api that carousel provide.

**Comment by mmahalwy** [comment]
woot! @mr47

**Comment by boobooninja** [comment]
+1

**Comment by barinbritva** [comment]
+1

**Comment by marcusbrose** [comment]
+1

**Comment by charlesbodman** [comment]
+1

**Comment by kenwheeler** [comment]
the people have spoken. expect it in the near future.

**Comment by mr47** [comment]
@kenwheeler i can submit a PR with 
https://github.com/mr47/nuka-carousel-autoscroll it works and pretty fast.

**Comment by charlesbodman** [comment]
For those who want a barebones auto carousel (ES6)

```javascript
import React, {Component} from 'react';
import Carousel from 'nuka-carousel';


class AutoCarousel extends Component {
	
	constructor()
	{
		super();
		this.autoPlayTimeout = false;
	}

	componentWillUnmount() {
		this.stopAutoSlide();
	}

	componentDidMount() {
		this.autoSlide();
	}

	stopAutoSlide()
	{
		clearTimeout(this.autoPlayTimeout);
	}

	autoSlide()
	{
		var carousel = this.carousel;
		
		var carouselState = carousel.state;

		var nextSlide = carouselState.currentSlide + 1;
		
		if(nextSlide >= carouselState.slideCount)
		{
			nextSlide = 0;
		}

		this.stopAutoSlide();
		this.autoPlayTimeout = setTimeout(carousel.goToSlide.bind(null,nextSlide),this.props.autoTime);	
	}

	afterSlide()
	{
		this.autoSlide();
	}

	render()
	{
		return (<Carousel ref={(c)=>this.carousel = c} {...this.props } afterSlide={this.afterSlide.bind(this)} >
					{this.props.children}
				</Carousel>);
	}
}

module.exports = AutoCarousel;
```


**Use it as normal with all nuka options**

```
<AutoCarousel  slidesToShow={1}  dragging={true} autoTime={500}>
     <img src="http://placehold.it/350x150"/>
     <img src="http://placehold.it/350x150"/>
</AutoCarousel>

**Comment by mr47** [comment]
@charlesbodman Sorry but your solution has poor perfomance, you can check this by using https://github.com/crysislinux/chrome-react-perf

<img width="960" alt="2016-05-18 08 18 40" src="https://cloud.githubusercontent.com/assets/651943/15348235/9d2e02e8-1cd1-11e6-92e4-67f74e610e9b.png">

**NukaCarouselAutoscroll:**
<img width="960" alt="2016-05-18 08 20 25" src="https://cloud.githubusercontent.com/assets/651943/15348242/a6846b20-1cd1-11e6-94f2-abddd6ade5ac.png">

**Comment by charlesbodman** [comment]
Hmm, i'll have to look at it. You can see by the code, it's incredibly straight forward. Not sure where the bottleneck would be. 

**Edit**

**Comment by charlesbodman** [comment]
**Fixed**

Two things come into play.

**First**
The following should be added to the autoplay carousel
https://gist.github.com/charlesbodman/88a58f67fb12fa0ff81acc59322ff15b
```javascript
shouldComponentUpdate(nextProps, nextState) {
	return shallowCompare(this, nextProps, nextState);
}
```

**Second**
Another thing is decorators.
If you are using the default nuka-carousel decorators, you are going to have wasted rendering.

The best thing you can do is provide custom decorators and provide a shouldComponentUpdate to them as well.

```javascript
let decorators = [{
	component:React.createClass({
		shouldComponentUpdate:function(nextProps, nextState){
			let should_update = false;
			if(this.props.currentSlide !== nextProps.currentSlide){
				should_update = true;
			}
			return should_update;
	},

....

```

**Comment by mr47** [comment]
@charlesbodman nice :+1:

**Comment by kenwheeler** [comment]
done on master

**Comment by erichdiniz** [comment]
@charlesbodman how does I remove those "next, prev"buttons from the slider?
