### ISSUE TITLE
More example usage

### ISSUE THREAD

**Issue by morenoh149** [kenwheeler/nuka-carousel#6]
Great project ken.

I'm trying to use this component but am running into issues. The project page shows how to make a carousel out of many images. But how do I make a carousel out of many react components?
Is that possible?
I tried
```javascript
var React = require('react/addons'),
    tweenState = require('react-tween-state'),

    // # mixins
    StateStreamMixin = require('../util/stateStreamMixin'),
    Carousel = require('nuka-carousel');

var Work = React.createClass({
  mixins: [
    tweenState.Mixin,
    StateStreamMixin,
    Carousel.ControllerMixin
  ],

    return (
      <Carousel>
        <section
          id='work'
          className='work'>
                 ...
        </section>
      </Carousel>
    );
  }
});

module.exports = Work;
```
The browser complains `Uncaught TypeError: children.map is not a function` 
![screenshot 2015-05-08 16 52 00](https://cloud.githubusercontent.com/assets/587438/7547469/96594312-f5a2-11e4-81a7-3dbb7c2689e3.png) https://github.com/kenwheeler/nuka-carousel/blob/954f616962d71c42878a73485a6ceef6505970c3/lib/carousel.js#L427

**Comment by kenwheeler** [comment]
Hey so whats happening here, is that the slides are intended to be direct children. Because you wrap it in a section, the map doesn't work because this.props.children is returning a node rather than an array, as it does when only one element is present.

**Comment by kenwheeler** [comment]
That said, I should probably validate that children are present and handle accordingly, so I'll leave this open.

**Comment by morenoh149** [comment]
so the only valid children types are pure html elements? Still not clear if I can make a carousel of react components.

**Comment by kenwheeler** [comment]
No , it works with components, you just need more than one

**Comment by morenoh149** [comment]
Okay. Simply putting two `section` components in Nuka slider. I get a different error.
![screenshot 2015-05-11 11 35 09](https://cloud.githubusercontent.com/assets/587438/7572293/dc416630-f7d1-11e4-9585-2dcdd0dd60d2.png)
Let me know if I should make different issue.

**Comment by kenwheeler** [comment]
What version of react are you using?

**Comment by morenoh149** [comment]
0.12.1 I could try upgrading it. I'm overdue.

**Comment by chaseadamsio** [comment]
`findDOMNode` was introduced in `v0.13.0` (From [React Release Notes on Github]( https://github.com/facebook/react/releases/tag/v0.13.0)

@morenoh149 I think you're on the right track considering bumping your `react` version to `v0.13.0`.
