### ISSUE TITLE
React 15.0 support?

### ISSUE THREAD

**Issue by sompylasar** [kenwheeler/nuka-carousel#70]
It's already RC2: https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html

**Comment by bogas04** [comment]
And it released today.

**Comment by kenwheeler** [comment]
Sorry, was on vacation, just got back and merged the compat update. I'll cut a release, just  waiting on a rebase on one of the latest PRs

**Comment by sompylasar** [comment]
@kenwheeler could you please release the react@15 compat?

**Comment by sompylasar** [comment]
Sadly, the change in #73 is not enough because `react-tween-state` specifies the peer dependency, too:
https://github.com/chenglou/react-tween-state/issues/57
https://github.com/chenglou/react-tween-state/pull/55
When the above is merged, `nuka-carousel` will have to follow and update, too.

**Comment by kenwheeler** [comment]
@sompylasar what happens when you try and install master? you get an unmet warning for tween state?

**Comment by sompylasar** [comment]
@kenwheeler Yes, exactly. And `npm@3` refuses to rebuild the shrinkwrap because of that. For now, I've made a fork with a proper dependency: https://github.com/sompylasar/nuka-carousel/commit/a9d871b7c46b9a1a3d7c3f599b5d9d2df3f810c8

**Comment by kennetpostigo** [comment]
Was this fixed @sompylasar? I'm currently debating to use `nuka` or `react-slick` not sure if they support `react v15.0` as of yet.

**Comment by sompylasar** [comment]
@kennetpostigo I use `"nuka-carousel": "^1.2.0",` with `"react": "^15.0.2",` without issues.

**Comment by kennetpostigo** [comment]
Thank you!
