### ISSUE TITLE
React Mixins Are Dead in ES6.

### ISSUE THREAD

**Issue by minooo** [kenwheeler/nuka-carousel#74]
Today , es6 is very popular in FrontEnd.
I hope you give a solution to solve the incompatible
![image](https://cloud.githubusercontent.com/assets/9410091/14422716/bcf3b912-000a-11e6-923d-0fe1f3f963ef.png)

Thank you very much!

**Comment by kenwheeler** [comment]
I think in a es6 class based scenario, I would probably use the slideIndex prop along with a `ref` reference.
