### ISSUE TITLE
peerinvalid while installing

### ISSUE THREAD

**Issue by rapahelkottakal** [kenwheeler/nuka-carousel#78]
**ERROR**
npm ERR! peerinvalid The package react-dom does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer nuka-carousel@1.1.2 wants react-dom@^0.14.3

**Local dependencies**
"dependencies": {
    "react-dom": "~15.0.1",
    "normalize.css": "~4.0.0",
    "react": "~15.0.1",
    "react-imageloader": "~2.1.0"
  },
  "devDependencies": {
    "react-hot-loader": "~1.3.0",
    "babel-loader": "~6.2.4",
    "webpack-dev-server": "~1.14.1",
    "webpack": "~1.12.15",
    "babel-core": "~6.7.6",
    "babel-preset-es2015": "~6.6.0",
    "babel-preset-react": "~6.5.0",
    "file-loader": "~0.8.5",
    "style-loader": "~0.13.1",
    "css-loader": "~0.23.1",
    "es6-promise": "~3.1.2"
  }

**Comment by roblabla** [comment]
This seems to be fixed on master per 87281d3c365cc22c98ec5b88343bc0848a2ff891 . Could we get this released on npm ?

**Comment by Joneser** [comment]
@kenwheeler Could this please be published to npm for consumption?

**Comment by kenwheeler** [comment]
i'll get it released today, sorry

**Comment by chmac** [comment]
@kenwheeler Firstly, thanks for this plugin, saved us a load of time.

Any update on pushing this version to NPM? If it's about to hit, then we'll hold off and try installing it again on Monday. Right now we can't get it to run.

**Comment by kenwheeler** [comment]
Didn't really want to, but I forked tween state and now depend on my 0.15 compatible fork. If tween-state gets 0.15 support, i'll republish with that dep, otherwise, I'll work on phasing this out. 1.2.0 is now 0.15 compatible.

**Comment by chmac** [comment]
@kenwheeler Awesome, thanks a lot. Had disabled the carousel for a project, will get it back online tomorrow, deadline is the end of the week, so really appreciate you deploying this. :+1: :+1: :+1:
