### ISSUE TITLE
Loop to first/last

### ISSUE THREAD

**Issue by heltonvalentini** [kenwheeler/nuka-carousel#8]
Is there anyway to loop slides ? Like when on the last slide onSwype redirect to first.

**Comment by sabeurthabti** [comment]
this would be great +1

**Comment by shouze** [comment]
:+1:

**Comment by jesse-wang** [comment]
+1

**Comment by rongierlach** [comment]
+1

**Comment by rongierlach** [comment]
For the time being I'm implementing a solution using the <a href="https://github.com/kenwheeler/nuka-carousel#decorators">decorators property</a> and some custom click-handling.

```coffeescript
render: ->
	base = @
	decorators = [
		{
			component: React.createClass
				displayName: 'DecoratorRight'
				render: ->
					clickHandler = =>
						if @props.currentSlide is base.state.slides.length - 1
							@props.goToSlide 0
						else
							@props.nextSlide()
					return(
						<i className="fa fa-chevron-right" onClick={clickHandler}></i>
					)
			position: "CenterRight"
			style:
				marginRight: "1em"
				fontSize: "2em"
				padding: "0 0.18em"
				display: "block"
				color: "black"
				backgroundColor: "white"
				paddingTop: "0.1em"
				paddingRight: "0.1em"
				cursor: "pointer"

		}
		{
			component: React.createClass
				displayName: 'DecoratorLeft'
				render: ->
					clickHandler = =>
						if @props.currentSlide is 0
							@props.goToSlide base.state.slides.length - 1
						else
							@props.previousSlide()
					return(
						<i className="fa fa-chevron-left" onClick={clickHandler}></i>
					)
			position: "CenterLeft"
			style:
				marginLeft: "1em"
				fontSize: "2em"
				padding: "0 0.18em"
				display: "block"
				color: "black"
				backgroundColor: "white"
				paddingTop: "0.1em"
				paddingLeft: "0.1em"
				cursor: "pointer"
		}
	]
        return(
        <div>
                <Carousel decorators={decorators}/>
                        {slides}
                </Carousel>
        </div>
        )
```

**Comment by hanwencheng** [comment]
or you can simply add the `nextSlide` and `previousSlide` function in the `/src`, it just two line of code, with a `%` operator

**Comment by boobooninja** [comment]
+1

**Comment by whynot123** [comment]
+1 infinite looping would be great

**Comment by lauterry** [comment]
There is a prop for that 

```wrapAround = {true} ```

See https://github.com/kenwheeler/nuka-carousel#wraparound

**Comment by sabeurthabti** [comment]
@lauterry well we all didn't read the docs haha

**Comment by heltonvalentini** [comment]
@sabeurthabti well we all should check issue's date.
Closing this since `wrapAround` on https://github.com/kenwheeler/nuka-carousel/commit/6cc20be2a3e23b017ac2efb5bec550ecc2c045bf

**Comment by mcianc** [comment]
+1 infinite looping would be great

**Comment by IronGhost63** [comment]
wrapAround really not make sense that will make this infinite loop

**Comment by travisdmathis** [comment]
+1 wrapAround is not the same as an infinite loop..

**Comment by felipemendes1994** [comment]
I made the transition from the last slide to the first one in another way... It was working but not like I expected. So I decided to search and I found this forum.... I swear to you that I read the documentation 30 times and I didn't see the prop wrapAround..... Well... It worked to me exactly like I wanted!!! Thanks lauterry.
