### ISSUE TITLE
Inside tab component not working properly

### ISSUE THREAD

**Issue by manimuthukumar6** [kenwheeler/nuka-carousel#93]
Hi ,

I want to implement this carousel inside tab component.But its'not working properly because of the hidden element not able to find width and height. So any trigger or re-render method to calculate the slider dimension while clicking the tab on so that I can trigger ?

**Comment by prrraveen** [comment]
@manimuthukumar6  , I am having the same issue. how to did you solve it?

**Comment by prrraveen** [comment]
I fixed it by setting CSS.
```
tab .inactive {
 display: block;
position: relative;
left:  -10000px
}

tab .active {
left: 0
}
```
